project:
  type: website
  output-dir: docs

website:
  favicon: "favicon.ico"
  site-url: "https://sharleenw.github.io"
  search: FALSE
  navbar:
    left:
      - text: "Home"
        file: "index.qmd"
      - about.qmd
      - text: "Resume"
        file: "sharleen_weatherley_resume.pdf"
      - icon: github
        href: https://github.com/sharleenw
      - icon: mastodon
        href: https://fosstodon.org/@sharleen
      - icon: linkedin
        href: https://www.linkedin.com/in/sharleenw
format:
  html:
    theme: minty
    css: styles.css

editor: visual

